version: '3.8'

services:
  nginx-proxy:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /opt/ssl-certs:/etc/nginx/certs:ro
    networks:
      - nginx-proxy-network
    restart: always

networks:
  nginx-proxy-network:
    external: true 